
spring.datasource.url=jdbc:mariadb://localhost:3306/cystation
spring.datasource.username=cytech
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.web.locale=fr_FR
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:Data/article.sql
spring.jpa.defer-datasource-initialization=true